### **Basics of `NumPy`**

> Main package for scientific computing in python

#### **Install the package**

In [2]:
# Depending upon which package manager we're using

# !conda install numpy
# !pip install numpy

#### **Import the package**

In [4]:
import numpy as np

#### **Advantages of using NumPy arrays**

- NumPy arrays work like traditional C arrays and are rigid and fast, unlike python lists which are slow
- An array obj in NumPy is called `ndarray` (n-dimensional array)

#### **Create a NumPy array**

In [5]:
array_1D = np.array([25, 12, 1997])
array_1D

array([  25,   12, 1997])

- Another way is to use `np.arange()`
- This function will return an array of evenly spaced values within a given interval

In [6]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Start a 1, end at 20, step size of 3
c = np.arange(1, 20, 3)
c

array([ 1,  4,  7, 10, 13, 16, 19])

- Use `np.linspace()` to get `n` evenly spaced values in an interval

In [9]:
# Give me 5 evenly spaced elements in the range 0...100
linspaced_array = np.linspace(0, 100, 5)
linspaced_array

array([  0.,  25.,  50.,  75., 100.])

- All of these functions take optional argument `dtype` to define the datatype of array

In [10]:
c_int = np.arange(1, 20, 3, dtype = int)
c_int

array([ 1,  4,  7, 10, 13, 16, 19])

- `np.ones()` returns a new array with all values set to 1

In [11]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

- `np.zeros()` returns a new array with all values set to 0

In [13]:
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

- `np.empty()` returns an un-initialized array

In [14]:
empty_array = np.empty(5)
empty_array

array([0., 0., 0., 0., 0.])

- `np.random.rand()` returns a new array with values chosen at random between 0 and 1

In [15]:
random_array = np.random.rand(5)
random_array

array([0.58714389, 0.39828268, 0.2685886 , 0.01263349, 0.867236  ])

#### **Multi-dimensional arrays**

In [16]:
array_2D = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

- `np.reshape()` can be used to re-arrange elements of an array into a new shape

In [17]:
array_1D = np.array([1, 2, 3, 4, 5, 6])

array_multiD = np.reshape(array_1D, (2, 3))
array_multiD

array([[1, 2, 3],
       [4, 5, 6]])

#### **Finding size, shape and dimension**

- `ndarray.ndim` to get dimensions of the array

In [18]:
array_multiD.ndim

2

- `ndarray.shape` to get the shape of the array

In [19]:
array_multiD.shape

(2, 3)

- `ndarray.size` returns the number of elements in the array

In [20]:
array_multiD.size

6

#### **Array math**

In [21]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

- **Addition**

In [23]:
addition = arr_1 + arr_2
addition

array([ 3,  7, 11])

- **Subtraction**

In [24]:
subtraction = arr_1 - arr_2
subtraction

array([1, 1, 1])

- **Multiplication** of two 1D arrays, elementwise

In [25]:
multiplication = arr_1 * arr_2
multiplication

array([ 2, 12, 30])

#### **Multiplying a vector with a scalar (broadcasting)**

In [26]:
vector = np.array([1, 2, 3])
vector * 2

array([2, 4, 6])

#### **Indexing and slicing**

- **Indexing**

In [27]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [28]:
a_2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a_2D[2][1]

8

- **Slicing**

In [30]:
sliced_array = a[1:4]
sliced_array

array([2, 3, 4])

In [31]:
sliced_array = a[:3]
sliced_array

array([1, 2, 3])

In [32]:
sliced_array = a[2:]
sliced_array

array([3, 4, 5])

In [33]:
# Get every 2nd element from array
sliced_array = a[::2]
sliced_array

array([1, 3, 5])

In [36]:
sliced_array_2D = a_2D[0:2]
sliced_array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
sliced_array_2D = a_2D[1:3]
sliced_array_2D

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
# Get the 2nd column
sliced_column = a_2D[:, 1]
sliced_column

array([2, 5, 8])

#### **Stacking**

In [39]:
a1 = np.array([
    [1, 1],
    [2, 2]
])

a2 = np.array([
    [3, 3],
    [4, 4]
])

a1, a2

(array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]]))

- `np.vstack()` is used to stack vertically

In [40]:
vertical_stacking = np.vstack((a1, a2))
vertical_stacking

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

- `np.hstack()` is used to stack horizontally

In [41]:
horizontal_stacking = np.hstack((a1, a2))
horizontal_stacking

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])