## **Solving Linear Systems: 3 variables**

#### **Packages**

In [1]:
import numpy as np

### **Representing and solving a system of linear equations using matrices**

#### **System of linear equations using matrices**

In [2]:
A = np.array([
    [4, -3, 1],
    [2, 1, 3],
    [-1, 2, -5]
], dtype = np.dtype(float))
b = np.array([-10, 0, 17], dtype = np.dtype(float))

A, b

(array([[ 4., -3.,  1.],
        [ 2.,  1.,  3.],
        [-1.,  2., -5.]]),
 array([-10.,   0.,  17.]))

In [ ]:
A.shape, b.shape

In [ ]:
X = np.linalg.solve(A, b)
X

In [ ]:
det_A = np.linalg.det(A)
print(f'{det_A:.2f}')

### **Solving system of linear equations using row reduction**

#### **Preparation of row reduction**

In [3]:
A_system = np.hstack((A, b.reshape(3, 1)))
A_system

array([[  4.,  -3.,   1., -10.],
       [  2.,   1.,   3.,   0.],
       [ -1.,   2.,  -5.,  17.]])

#### **Functions of elementary operations**

In [5]:
def multiply_row(M, row_num, multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * multiple
    
    return M_new

In [6]:
def add_rows(M, row_num_1, row_num_2, multiple):
    M_new = M.copy()
    M_new[row_num_2] = multiple * M_new[row_num_1] + M_new[row_num_2]
    
    return M_new

In [7]:
def swap_rows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    
    return M_new

#### **Row reduction and solution of linear system**

In [8]:
A_ref = swap_rows(A_system, 0, 2)
A_ref

array([[ -1.,   2.,  -5.,  17.],
       [  2.,   1.,   3.,   0.],
       [  4.,  -3.,   1., -10.]])

In [9]:
A_ref = add_rows(A_ref, 0, 1, 2)
A_ref

array([[ -1.,   2.,  -5.,  17.],
       [  0.,   5.,  -7.,  34.],
       [  4.,  -3.,   1., -10.]])

In [10]:
A_ref = add_rows(A_ref, 0, 2, 4)
A_ref

array([[ -1.,   2.,  -5.,  17.],
       [  0.,   5.,  -7.,  34.],
       [  0.,   5., -19.,  58.]])

In [11]:
A_ref = add_rows(A_ref, 1, 2, -1)
A_ref

array([[ -1.,   2.,  -5.,  17.],
       [  0.,   5.,  -7.,  34.],
       [  0.,   0., -12.,  24.]])

In [12]:
A_ref = multiply_row(A_ref, 2, -1/12)
A_ref

array([[-1.,  2., -5., 17.],
       [ 0.,  5., -7., 34.],
       [-0., -0.,  1., -2.]])

In [13]:
x_3 = -2
x_2 = (A_ref[1, 3] - (A_ref[1, 2] * x_3)) / A_ref[1, 1]
x_1 = (A_ref[0, 3] - (A_ref[0, 2] * x_3) - (A_ref[0, 1] * x_2)) / A_ref[0, 0]

x_1, x_2, x_3

(1.0, 4.0, -2)